version: 2.1

executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:12
    environment:
      TZ: /usr/share/zoneinfo/Asia/Tokyo

commands:
  attach:
    steps:
      - attach_workspace:
          at: ~/workspace
  persist:
    steps:
      - persist_to_workspace:
          root: ~/workspace
          paths:
            - ./*

jobs:
  setup:
    executor: default
    steps:
      - run:
          name: System information
          command: |
            echo "Node $(node -v)"
            echo "Yarn v$(yarn -v)"
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Setup
          command: |
            yarn setup
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - persist
  build:
    executor: default
    steps:
      - attach
      - run:
          name: Build
          command: |
            yarn build
  deploy:
    executor: default
    parameters:
      stage:
        type: enum
        enum: [ "dev", "prd" ]
    steps:
      - attach
      - deploy:
          command: |
            yarn deploy --stage << parameters.stage >>


workflows:
  build-deploy-flow:
    jobs:
      - setup
      - build:
          context: spajam-2019-qualification
          requires:
            - setup
      - deploy:
          stage: dev
          context: spajam-2019-qualification
          requires:
            - build
          filters:
            branches:
              only: master
